tup = ("muskan","kushwah",123,867,"i miss you","book",890)
print(tup)
print(type(tup))
print("********************")
print(all(tup))
print("+++++++++++++++++++++++")
print(len(tup))
print("*************************")
print(tup.index(867))
print(tup.count(8))
